name: Swift Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'
    
    - name: Install dependencies
      run: |
        brew update
        brew install xcbeautify
    
    - name: Show project structure
      run: |
        ls -la
        swift package describe
      continue-on-error: true
      
    - name: Verify Package.swift
      run: swift package dump-package
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: |
        swift test -v 2>&1 | xcbeautify --renderer github-actions
      
    - name: Archive test logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-logs
        path: .build/debug/testlogs
        retention-days: 7
